# Default settings for this application.
# You can override this settings by writing a config-local.yml file

# Docker host server info
host: ""

# Settings for each service
php_todo_api:
  enabled: true
  port: 8001

go_todo_api:
  enabled: false
  port: 8002

react_todo_web:
  enabled: true
  port: 8100

todo_api_gateway:
  enabled: true
  port: 443
  todo_api_service: "php_todo_api"
  web_port: 8443

mongo:
  port: 27017
  database: "todo"

mariadb:
  port: 3306
  database: "todo"
  user: "root"
  password: "pass"
