version: '2'

services:
  {{if (eq .Env.config_php_todo_api_enabled "true")}}
  php_todo_api:
    volumes:
      - ./php_todo_api/app:/var/www/api/app
      - ./php_todo_api/bootstrap:/var/www/api/bootstrap
      - ./php_todo_api/database:/var/www/api/database
      - ./php_todo_api/public:/var/www/api/public
      - ./php_todo_api/resources:/var/www/api/resources
      - ./php_todo_api/tests:/var/www/api/tests
      - ./php_todo_api/composer.json:/var/www/api/composer.json
      - ./php_todo_api/composer.lock:/var/www/api/composer.lock
    entrypoint:
      - sleep
    command:
      - "1000000000"
    environment:
      APP_ENV: local
  {{end}}
  {{if (eq .Env.config_go_todo_api_enabled "true")}}
  go_todo_api:
    volumes:
      - ./go_todo_api:/go/src/todo_center/go_todo_api
    entrypoint:
      - sleep
    command:
      - "1000000000"
    environment:
      GIN_MODE: debug
  {{end}}
  {{if (eq .Env.config_react_todo_web_enabled "true")}}
  react_todo_web:
    volumes:
      - ./react_todo_web/src:/usr/src/app/src
      - ./react_todo_web/test:/usr/src/app/test
      - ./react_todo_web/server.js:/usr/src/app/server.js
      - ./react_todo_web/package.json:/usr/src/app/package.json
      - ./react_todo_web/webpack.local.config.js:/usr/src/app/webpack.local.config.js
      - ./react_todo_web/webpack.production.config.js:/usr/src/app/webpack.production.config.js
    entrypoint:
      - sleep
    command:
      - "1000000000"
    ports:
      - "{{ .Env.config_react_todo_web_dev_port }}:9090"
    environment:
      PRODUCTION: ""
      SERVER_RENDERING: ""
      DEV_HOST: {{ .Env.config_host }}
      DEV_PORT: {{ .Env.config_react_todo_web_dev_port }}
  {{end}}
